DevCar1_MVC/Models/Contact.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DevCar1_MVC.Models
{
    public class Contact
    {
        [Required(ErrorMessage = "این فیلد اجباری است")]
        [MinLength(3,ErrorMessage = "حد اقل طول نام 3 کاراکتر است")]
        [MaxLength(100, ErrorMessage = "حد اکثر طول نام 100 کاراکتر است")]

        public string Name { get; set; }
        [Required(ErrorMessage = "این فیلد اجباری است")]

        [EmailAddress(ErrorMessage = "مقدار وارد شده ایمل صحیح نیست")]
        public string Email { get; set; }
        [Required(ErrorMessage = "این فیلد اجباری است")]
        public string Message { get; set; }
        [Required(ErrorMessage = "این فیلد اجباری است")]
        public string Service { get; set; }
    }
}

DevCar1_MVC/Controllers/HomeController.cs
using System;
using DevCar1_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Microsoft.AspNetCore.Http;

namespace DevCar1_MVC.Controllers
{
    public class HomeController : Controller
    {
        

        public HomeController()
        {
           
        }

        public ViewResult Index()
        {
            return View();
        }
        //[HttpPost]
        //public JsonResult Contact(IFormCollection form)
        //{
        //    var name = form["name"];
        //    return Json(Ok());
        //}
        [HttpGet]
        public IActionResult Contact()
        {
            var model=new Contact();
            return View(model);
        }

        [HttpPost]
        public IActionResult Contact(Contact model)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.error = "اطلاعات وارد شده  صحیح نیست";
                return View(model);
            }

            ViewBag.success = "پیغام شما با موفقیت ارسال شد با تشکر";
            return View();
            // return RedirectToAction("Index");
        }

        

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DevCar1_MVC/ViewComponents/LatestArticlesViewComponent.cs
using System;
using System.Collections.Generic;
using System.Xml;
using DevCar1_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Razor.Language.Extensions;

namespace DevCar1_MVC.ViewComponents
{
    public class LatestsArticlesViewComponent : ViewComponent
    {

        public IViewComponentResult Invoke()
        {

            var articles = new List<Article1>()
            {
                new Article1(id:1,title:"اموزش asp.net core 5",discription:"اموزش همراه با رفع اشکال و 3 پروژه انلاین",image:"blog-post-thumb-card-1.jpg"),
                new Article1(id:2,title:"اموزش gitوgithub",discription:"اموزش کاملا پروژه محور",image:"blog-post-thumb-card-2.jpg"),
                new Article1(id:3,title:"اموزش htmlوcss",discription:"اموزش همراه با ارایه مدرک بین المللی",image:"blog-post-thumb-card-3.jpg"),
                new Article1(id:4,title:"اموزش java script",discription:"اموزش های رسمی توسط مدرس رسمی ماکرو سافت",image:"blog-post-thumb-card-4.jpg"),

            };
            return View("LatestsArticles", articles);



        }


    }



}

DevCar1_MVC/ViewComponents/ProjectsViewComponent.cs
using System.Collections.Generic;
using System.Linq;
using DevCar1_MVC.Controllers;
using DevCar1_MVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace DevCar1_MVC.ViewComponents
{
    public class ProjectsViewComponent  :ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            var Projects = new List<Project1>()
            {
                new Project1(id:1,name:"تاکسی",discription:"پروژه تاکسی رانی های مختلف در بازار ", image:"project-1.jpg",client:"snap"),
                new Project1(id:2,name:"زود فود",discription:"درخواست انلاین غذا ",image:"project-2.jpg", client:"zoodfood"),
                new Project1(id:3,name:"Mobile",discription:"پروژه تعمیر و سفارش انواع تلفن همراه ",image:"project-3.jpg", client:"mobile"),
                new Project1(id:4,name:"مداری",discription:"سیستم مدیریت یکپارچه مدارس ",image:"project-7.jpg", client:"madares"),

            };
            return View("_Projects",Projects);
        }
    }
}

DevCar1_MVC/Views/Home/Contact.cshtml
@model Contact
@{
    ViewData["Title"] = "ارتباط با ما";
}
<section class="cta-section theme-bg-light py-5">
    <div class="container text-center single-col-max-width">
    <h2 class="heading">ارتباط با ما</h2>
        <div class="intro">
            <p>
                شما می توانید از طریق فرم زیر با ما ارتباط بگیرید. لطفا پس از پرکردن آیتم ها، پیغام مورد نظر را
                نوشته و ارسال کنید.
            </p>
            <p>از طریق شبکه های اجتماعی با ما در ارتباط باشید</p>
            <ul class="list-inline mb-0">
                <li class="list-inline-item mb-3">
                    <a class="twitter" href="#">
                        <i class="fab fa-twitter fa-fw fa-lg"></i>
                    </a>
                </li>

                <li class="list-inline-item mb-3">
                    <a class="linkedin" href="#">
                        <i class="fab fa-linkedin-in fa-fw fa-lg"></i>
                    </a>
                </li>
                <li class="list-inline-item mb-3">
                    <a class="github" href="#">
                        <i class="fab fa-github-alt fa-fw fa-lg"></i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a class="instagram" href="#">
                        <i class="fab fa-instagram fa-fw fa-lg"></i>
                    </a>
                </li>
                <li class="list-inline-item mb-3">
                    <a class="stack-overflow" href="#">
                        <i class="fab fa-stack-overflow fa-fw fa-lg"></i>
                    </a>
                </li>
                <li class="list-inline-item mb-3">
                    <a class="medium" href="#">
                        <i class="fab fa-medium-m fa-fw fa-lg"></i>
                    </a>
                </li>
                <li class="list-inline-item mb-3">
                    <a class="codepen" href="#">
                        <i class="fab fa-codepen fa-fw fa-lg"></i>
                    </a>
                </li>
            </ul>
        </div>
        </div>
</section>
<section class="contact-section px-3 py-5 p-md-5">
    <div class="container">
        @if (!string.IsNullOrWhiteSpace(ViewBag.success))
        {
            <div class="alert-success p-5">
            <p>@ViewBag.success</p>
            </div>
        } 
        @if (!string.IsNullOrWhiteSpace(ViewBag.error))
          {
              <div class="alert-danger p-5" >
                  <p>@ViewBag.error</p>
              </div>
          }
        
        <form id="contact-form" class="contact-form col-lg-8 mx-lg-auto" method="post" asp-action="Contact">
            <h3 class="text-center mb-3">در دسترس باشید!</h3>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label class="sr-only" asp-for="Name">نام</label>
                    <input type="text" class="form-control" asp-for="Name" placeholder="نام">
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6">
                    <label class="sr-only" asp-for="Email">ایمیل</label>
                    <input type="email" class="form-control" asp-for="Email" placeholder="ایمیل">
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group col-12">
                    <select asp-for="Service" class="custom-select">
                        <option selected>سرویس مورد نظر خود را انتخاب کنید...</option>
                        <option value="basic">نقره ای</option>
                        <option value="standard">طلایی</option>
                        <option value="premium">پلاتین</option>
                        <option value="not sure">الماس</option>
                    </select>
                </div>
                <div class="form-group col-12">
                    <label class="sr-only">پیغام شما</label>
                    <textarea class="form-control" asp-for="Message"
                              placeholder="پیغام خود را وارد نمایید ..." rows="10"></textarea>
                </div>
                <div class="form-group col-12">
                    <button type="submit" class="btn btn-block btn-primary py-2">ارسال</button>
                </div>
            </div>
        </form>
    </div>
</section>

DevCar1_MVC/Views/Home/Index.cshtml
@model List<IndexModel>

@{
    ViewData["Title"] = "صفحه اصلی";
}

<section class="about-me-section p-3 p-lg-5 theme-bg-light">
    <div class="container">
        <div class="profile-teaser media flex-column flex-lg-row">
            <img class="profile-image mb-3 mb-lg-0 ml-lg-5 mr-md-0" src="assets/images/me1.jpg" alt="">
            <div class="media-body">
                <h2 class="name font-weight-bold mb-1">علی ربیعی</h2>
                <div class="tagline mb-3">برنامه نویس ارشد</div>
                <div class="bio mb-4">
                    لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از
                    طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و
                    جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.
                </div>
                <div class="mb-4">
                    <a class="btn btn-primary mr-2 mb-3" href="http://www.atriya.com">
                        <i class="fas fa-arrow-alt-circle-right ml-2"></i>
                        <span class="d-none d-md-inline">
                            برو
                            به
                        </span> آتریا
                    </a>
                    <a class="btn btn-secondary mb-3" href="#">
                        <i class="fas fa-file-alt ml-2"></i>
                        <span class="d-none d-md-inline">مشاهده </span> نمونه کارها
                    </a>
                </div>
            </div>

        </div>
    </div>
</section>
@* loding partial view *@
@*<partial name="Projects"/>*@
@*@await Html.PartialAsync("Projects"new List<Project>())
    @await Html.PartialAsync("Projects")*@
@* loding view component *@

@await Component.InvokeAsync("Projects")
<div class="container">
    <hr>
</div>
@await Component.InvokeAsync("LatestsArticles")